name: Screenshots
on: [push]
jobs:
  screenshot:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Screenshot Main Page
      uses: SimobiSirOP/screenshot-website@main
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot-main-page.png
        width: 1600
        height: 700
        full-page: true
